# Project
group=net.conczin
java_version=25

# Common
minecraft_version=26.1.2
minecraft_version_range=[26.1.2, 26.2)
# https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Neoforge
neoforge_version=26.1.2.59-beta
neoforge_loader_version_range=[4,)

# Fabric
fabric_loader_version=0.19.2

# Mod options
mod_name=SelectiveBounds
mod_author=Luke100000
mod_id=selectivebounds
license=GPL-3.0
credits=
description=Hides the ugly block selection outline when not relevant.
mod_homepage=https://conczin.net/
mod_sources=https://github.com/Luke100000/SelectiveBounds
mod_issues=https://github.com/Luke100000/SelectiveBounds/issues

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
